const productos = [
  {
    id: 1,
    nombre: "Pan masa madre",
    precio: 100,
    Img: "./imagenes/imagenProductos/panmasamadre.png",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "Budin integral",
    precio: 200,
    Img: "./imagenes/imagenProductos/budin.png",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "Alfajor integral",
    precio: 300,
    Img: "./imagenes/imagenProductos/alfajores-integrales.png",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "Mermelada natural",
    precio: 400,
    Img: "./imagenes/imagenProductos/mermelada.png",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "Mix de frutos tropicales",
    precio: 500,
    Img: "./imagenes/imagenProductos/mix-tropical.png",
    cantidad: 1,
  },
  {
    id: 6,
    nombre: "Mantequilla de mani",
    precio: 600,
    Img: "./imagenes/imagenProductos/mantequilla-de-mani.png",
    cantidad: 1,
  },
  {
    id: 7,
    nombre: "Pre-pizza Integral",
    precio: 700,
    Img: "./imagenes/imagenProductos/pizza.png",
    cantidad: 1,
  },
  {
    id: 8,
    nombre: "Medialuna con semilla y stevia",
    precio: 800,
    Img: "./imagenes/imagenProductos/medialunas.png",
    cantidad: 1,
  },
];
